version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: healthy_summer_postgres
    restart: always
    environment:
      POSTGRES_USER: healthyuser
      POSTGRES_PASSWORD: healthypass
      POSTGRES_DB: healthydb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data"

  user-service:
    build: ./backend/user-service
    container_name: user_service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=healthyuser
      - DATABASE_PASSWORD=healthypass
      - DATABASE_NAME=healthydb

  activity-service:
    build: ./backend/activity-service
    container_name: activity_service
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=healthyuser
      - DATABASE_PASSWORD=healthypass
      - DATABASE_NAME=healthydb

  nutrition-service:
    build: ./backend/nutrition-service
    container_name: nutrition_service
    ports:
      - "8083:8083"
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=healthyuser
      - DATABASE_PASSWORD=healthypass
      - DATABASE_NAME=healthydb

  social-service:
    build: ./backend/social-service
    container_name: social_service
    ports:
      - "8084:8084"
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=healthyuser
      - DATABASE_PASSWORD=healthypass
      - DATABASE_NAME=healthydb

volumes:
  pgdata:
