version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: healthy_summer_postgres
    restart: always
    environment:
      POSTGRES_USER: healthyuser
      POSTGRES_PASSWORD: healthypass
      POSTGRES_DB: healthydb
    ports:  
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  pgadmin-data: